---
title: "ps_4"
author: "Stephanie Yao"
date: "February 25, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(gt)
```

```{r}
elections <- read_csv("ps_4_elections-poll-nc09-3.csv")
  
# support of democratic candidate
dems <- elections %>%
  filter(response == "Dem") %>%
  summarize(dems = n())

# support of republican candidate
reps <- elections %>%
  filter(response == "Rep") %>%
  summarize(reps = n())

# undecided
unds <- elections %>%
  filter(response == "Und") %>%
  summarize(unds = n())

# number of people with different values for gender and gender_combined
differing_gender <- elections %>%
  filter(gender != gender_combined) %>%
  summarize(differing_gender = n())

differing_ethnicity <- elections %>%
  filter(race_eth == "White", file_race_black != "White") %>%
  summarize(differing_ethnicity = n())
```
# Question 1
There were `r pull(dems)` respondents who supported the Democratic candidate.

There were `r pull(reps)-pull(unds)` more respondents who favored the Republican candidate than who were Undecided.

There are two gender variables (`gender` and `gender_combined`). There are `r ` individuals for whom these variables have different values.

# Question 3
```{r}
elections %>%
  select(educ, final_weight) %>%
  filter(educ != "[DO NOT READ] Refused") %>%
  ggplot(aes(x = final_weight, y = educ)) +
  geom_violinh(fill = 'white') +
  geom_jitter(alpha = 0.3) +
  labs(title = "More Educated Matter Less in North Carolina 9th",
       subtitle = "Poll gives more weight to people who are less likely to participate in polls",
       caption = "New York Times Upshot/Siena College 2018 live polls") +
  xlab("Weight Given to Respondent in Calculating Poll Results") +
  ylab(NULL)
```